corrected the shebang for unix scripts

diff --git a/docker/local/django/entrypoint b/docker/local/django/entrypoint
--- a/docker/local/django/entrypoint
+++ b/docker/local/django/entrypoint
@@ -1,45 +1,37 @@
-#!bin/bash
+#!/bin/bash
 
-#script will fail and exit if any command fails
-set -o errexit
+# #script will fail and exit if any command fails
+# set -o errexit
 
-# script will fail and exit when a pipe comamnd fails
-set -o pipefail
+# # script will fail and exit when a pipe comamnd fails
+# set -o pipefail
 
-#exit when uninitialised variable is used
-set -o nounset
+# #exit when uninitialised variable is used
+# set -o nounset
 
-if [ -z "${POSTGRES_USER}" ]; then
-    base_postgres_image_default_user='postgres'
-    export POSTGRES_USER="${base_postgres_image_default_user}"
-fi 
+export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
 
-export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_PORT}:${POSTGRES_HOST}:{POSTGRES_PORT}/${POSTGRES_DB}"
-
-python << END 
-import sys 
-import time
+postgres_ready() {
+python << END
+import sys
 import psycopg2
-suggest_unrecoverable_after = 30 
-start = time.time()
-while True: 
-    try:
-        psycopg2.connect(
-            dbname="${POSTGRES_DB}",
-            user="${POSTGRES_USER}",
-            password="${POSTGRES_PASSWORD}",
-            host="${POSTGRES_HOST}",
-            port="${POSTGRES_PORT}",
-        )
-        break
-    except psycopg2.OperationalError as error:
-        sys.stderr.write("Waiting for POstgreSQL to become avaiable..\n")
-        if time.time() - start > suggest_unrecoverable_after:
-            sys.stderr.write("This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))
-    time.sleep(3)
-
+try:
+   psycopg2.connect(
+      dbname="${POSTGRES_DB}",
+      user="${POSTGRES_USER}",
+      password="${POSTGRES_PASSWORD}",
+      host="${POSTGRES_HOST}",
+      port="${POSTGRES_PORT}",
+   )
+except psycopg2.OperationalError:
+   sys.exit(-1)
+sys.exit(0)
 END
+}
+until postgres_ready; do
+>&2 echo "Waiting for PostgreSQL to become available.....:-("
+sleep 1
+done
+>&2 echo "PostgreSQL is ready!!!!.....:-)"
 
->&2 echo "POSTGRESQL is available"
- 
- exec "$@"
+exec "$@"
diff --git a/docker/local/django/start b/docker/local/django/start
--- a/docker/local/django/start
+++ b/docker/local/django/start
@@ -1,14 +1,14 @@
-#!bin/bash
+#!/bin/bash
 
-#script will fail and exit if any command fails
-set -o errexit
+# #script will fail and exit if any command fails
+# set -o errexit
 
-# script will fail and exit when a pipe comamnd fails
-set -o pipefail
+# # script will fail and exit when a pipe comamnd fails
+# set -o pipefail
 
-#exit when uninitialised variable is used
-set -o nounset
+# #exit when uninitialised variable is used
+# set -o nounset
 
-python manage.py migrate --no-input
-python manage.py collectstatic --no-input
-exec python manage.py  runserver 0.0.0.0:8000
+python3 manage.py migrate --no-input
+python3 manage.py collectstatic --no-input
+python3 manage.py runserver 0.0.0.0:8000
